fix[expiration date] fix bug expiration date
orangerdev/sejoli-reward pull request #2
Opened 2022-07-08 08:56 UTC by asdzakky

2022-07-08 09:49 UTC, orangerdev requested changes

2022-07-08 09:49 UTC, orangerdev commented on models/reward.php
>          if($no_exp_date === false):
ini harusnya di If nya mas jadi 

`if(boolval($no_exp_date) === false):`

2022-07-08 12:26 UTC, asdzakky commented on models/reward.php
>          if($no_exp_date === false):
done pak

2022-07-11 03:18 UTC, orangerdev approved these changes

2022-07-11 03:18 UTC, merged